name: Sync OneDrive Folder to GitHub

on:
  # schedule:
  #   - cron: '0 * * * *' # Runs every hour
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup rclone
        uses: rclone/rclone-action@v2
        with:
          args: 'sync onedrive:/My Files/Documents/translations /github/workspace'

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated sync from OneDrive"
          git push
